package mas.agents;

import com.google.gson.Gson;
import com.google.gson.reflect.TypeToken;
import jade.core.AID;
import jade.core.Agent;
import jade.lang.acl.ACLMessage;
import com.sun.net.httpserver.HttpServer;
import com.sun.net.httpserver.HttpExchange;
import com.sun.net.httpserver.HttpHandler;

import java.io.*;
import java.lang.reflect.Type;
import java.net.InetSocketAddress;
import java.nio.charset.StandardCharsets;
import java.util.Map;

public class HttpBridgeAgent extends Agent {
    private HttpServer server;
    private final Gson gson = new Gson();
    private final int port = 8080;

    @Override
    protected void setup() {
        try {
            server = HttpServer.create(new InetSocketAddress(port), 0);
            server.createContext("/api/config", new ConfigHandler());
            server.createContext("/api/status", new StatusHandler());
            server.createContext("/api/start-negotiation", new StartNegotiationHandler());
            server.setExecutor(null);
            server.start();
            System.out.println("[HttpBridgeAgent] HTTP server started on http://localhost:" + port);
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    @Override
    protected void takeDown() {
        if (server != null) server.stop(0);
        System.out.println("[HttpBridgeAgent] stopped.");
        super.takeDown();
    }

    private class ConfigHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            if ("OPTIONS".equalsIgnoreCase(exchange.getRequestMethod())) {
                addCors(exchange);
                exchange.sendResponseHeaders(204, -1);
                return;
            }

            if (!"POST".equalsIgnoreCase(exchange.getRequestMethod())) {
                addCors(exchange);
                exchange.sendResponseHeaders(405, -1);
                return;
            }

            String body = readRequestBody(exchange);
            addCors(exchange);

            try {
                Type tt = new TypeToken<Map<String, Object>>() {}.getType();
                Map<String, Object> json = gson.fromJson(body, tt);

                StringBuilder sb = new StringBuilder();
                sb.append("# Generated by HttpBridgeAgent\n\n");
                if (json.containsKey("negotiation")) {
                    Map<String, Object> neg = (Map<String, Object>) json.get("negotiation");
                    if (neg.containsKey("maxRounds")) sb.append("negotiation.maxRounds=").append(neg.get("maxRounds")).append("\n");
                    if (neg.containsKey("discountRate")) sb.append("negotiation.discountRate=").append(neg.get("discountRate")).append("\n");
                    sb.append("\n");
                }
                if (json.containsKey("buyer")) {
                    Map<String, Object> b = (Map<String, Object>) json.get("buyer");
                    if (b.containsKey("acceptanceThreshold")) sb.append("buyer.acceptanceThreshold=").append(b.get("acceptanceThreshold")).append("\n");
                    if (b.containsKey("riskBeta")) sb.append("buyer.riskBeta=").append(b.get("riskBeta")).append("\n");
                    if (b.containsKey("gamma")) sb.append("buyer.gamma=").append(b.get("gamma")).append("\n");
                    sb.append("\n");
                }
                if (json.containsKey("weights")) {
                    Map<String, Object> w = (Map<String, Object>) json.get("weights");
                    if (w.containsKey("price")) sb.append("weights.price=").append(w.get("price")).append("\n");
                    if (w.containsKey("quality")) sb.append("weights.quality=").append(w.get("quality")).append("\n");
                    if (w.containsKey("delivery")) sb.append("weights.delivery=").append(w.get("delivery")).append("\n");
                    if (w.containsKey("service")) sb.append("weights.service=").append(w.get("service")).append("\n");
                    sb.append("\n");
                }
                if (json.containsKey("seller")) {
                    Map<String, Object> s = (Map<String, Object>) json.get("seller");
                    if (s.containsKey("acceptanceThreshold")) sb.append("seller.acceptanceThreshold=").append(s.get("acceptanceThreshold")).append("\n");
                    if (s.containsKey("riskBeta")) sb.append("seller.riskBeta=").append(s.get("riskBeta")).append("\n");
                    if (s.containsKey("gamma")) sb.append("seller.gamma=").append(s.get("gamma")).append("\n");
                    sb.append("\n");
                }

                try (Writer w = new BufferedWriter(new OutputStreamWriter(new FileOutputStream("config.properties"), StandardCharsets.UTF_8))) {
                    w.write(sb.toString());
                }

                System.out.println("[HttpBridgeAgent] Saved config.properties");

                ACLMessage msg = new ACLMessage(ACLMessage.INFORM);
                msg.addReceiver(new AID("tda", AID.ISLOCALNAME));
                msg.setProtocol("api-config");
                msg.setContent(body);
                send(msg);
                System.out.println("[HttpBridgeAgent] Sent config to TDA (protocol=api-config)");

                String resp = "Config saved and TDA notified";
                exchange.sendResponseHeaders(200, resp.getBytes(StandardCharsets.UTF_8).length);
                try (OutputStream os = exchange.getResponseBody()) {
                    os.write(resp.getBytes(StandardCharsets.UTF_8));
                }

            } catch (Exception ex) {
                ex.printStackTrace();
                String resp = "Error processing config: " + ex.getMessage();
                exchange.sendResponseHeaders(500, resp.getBytes(StandardCharsets.UTF_8).length);
                try (OutputStream os = exchange.getResponseBody()) { os.write(resp.getBytes(StandardCharsets.UTF_8)); }
            }
        }
    }

    private class StatusHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            addCors(exchange);
            String resp = "HttpBridgeAgent running";
            exchange.sendResponseHeaders(200, resp.getBytes(StandardCharsets.UTF_8).length);
            try (OutputStream os = exchange.getResponseBody()) { os.write(resp.getBytes(StandardCharsets.UTF_8)); }
        }
    }

    private class StartNegotiationHandler implements HttpHandler {
        @Override
        public void handle(HttpExchange exchange) throws IOException {
            if ("OPTIONS".equalsIgnoreCase(exchange.getRequestMethod())) {
                addCors(exchange);
                exchange.sendResponseHeaders(204, -1);
                return;
            }

            if (!"POST".equalsIgnoreCase(exchange.getRequestMethod())) {
                addCors(exchange);
                exchange.sendResponseHeaders(405, -1);
                return;
            }

            addCors(exchange);

            try {
                ACLMessage msg = new ACLMessage(ACLMessage.REQUEST);
                msg.addReceiver(new AID("tda", AID.ISLOCALNAME));
                msg.setContent("URGENT_DEMAND_CHANGE");
                send(msg);
                System.out.println("[HttpBridgeAgent] Sent immediate negotiation request to TDA");

                String resp = "{\"status\": \"Negotiation started\"}";
                exchange.sendResponseHeaders(200, resp.getBytes(StandardCharsets.UTF_8).length);
                try (OutputStream os = exchange.getResponseBody()) {
                    os.write(resp.getBytes(StandardCharsets.UTF_8));
                }

            } catch (Exception ex) {
                ex.printStackTrace();
                String resp = "{\"error\": \"" + ex.getMessage() + "\"}";
                exchange.sendResponseHeaders(500, resp.getBytes(StandardCharsets.UTF_8).length);
                try (OutputStream os = exchange.getResponseBody()) { 
                    os.write(resp.getBytes(StandardCharsets.UTF_8)); 
                }
            }
        }
    }


    private String readRequestBody(HttpExchange exchange) throws IOException {
        try (InputStream in = exchange.getRequestBody(); ByteArrayOutputStream baos = new ByteArrayOutputStream()) {
            byte[] buf = new byte[1024];
            int r;
            while ((r = in.read(buf)) != -1) baos.write(buf, 0, r);
            return baos.toString(StandardCharsets.UTF_8);
        }
    }

    private void addCors(HttpExchange exchange) {
        exchange.getResponseHeaders().add("Access-Control-Allow-Origin", "*");
        exchange.getResponseHeaders().add("Access-Control-Allow-Methods", "POST, GET, OPTIONS");
        exchange.getResponseHeaders().add("Access-Control-Allow-Headers", "Content-Type");
    }
}

